---
- name: Main playbook to clone and execute other playbooks
  hosts: localhost
  become: yes  # Some tasks might require sudo permissions
  tasks:
    - name: Ensure git is installed
      pacman:
        name: git
        state: present

    - name: Create a directory for the playbooks
      file:
        path: "/tmp/dotfiles_playbooks"
        state: directory
      become: no

    - name: Clone dotfiles repository
      git:
        repo: 'https://github.com/CEnjolras/dotfiles.git'
        dest: '/tmp/dotfiles_playbooks'
        depth: 1  # Shallow clone, get only the latest revision
        force: yes
      become: no

- import_playbook: /tmp/dotfiles_playbooks/playbooks/pacman_reflector.yml
- import_playbook: /tmp/dotfiles_playbooks/playbooks/yay.yml
- import_playbook: /tmp/dotfiles_playbooks/playbooks/terminal_fish_foot.yml
- import_playbook: /tmp/dotfiles_playbooks/playbooks/nvm.yml
- import_playbook: /tmp/dotfiles_playbooks/playbooks/hyprland.yml

- name: Cleanup - Remove the dotfiles_playbooks directory
  hosts: localhost
  become: no
  tasks:
    - name: Delete the dotfiles_playbooks directory
      file:
        path: "/tmp/dotfiles_playbooks"
        state: absent
