---
- name: Main playbook using include_tasks
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure git is installed
      pacman:
        name: git
        state: present

    - name: Remove the /tmp/playbooks directory if it exists
      file:
        path: "/tmp/playbooks"
        state: absent

    - name: Clone dotfiles repository to /tmp/playbooks
      git:
        repo: 'https://github.com/CEnjolras/dotfiles.git'
        dest: '/tmp/playbooks'
        depth: 1
        force: yes

    - name: Include pacman_reflector tasks
      include_tasks: '/tmp/playbooks/playbooks/pacman_reflector.yml'

    - name: Include yay tasks
      include_tasks: '/tmp/playbooks/playbooks/yay.yml'

    - name: Include terminal_fish_foot tasks
      include_tasks: '/tmp/playbooks/playbooks/terminal_fish_foot.yml'

    - name: Include nvm tasks
      include_tasks: '/tmp/playbooks/playbooks/nvm.yml'

    - name: Include hyprland tasks
      include_tasks: '/tmp/playbooks/playbooks/hyprland.yml'

    - name: Cleanup - Remove the dotfiles_playbooks directory
      file:
        path: "/tmp/playbooks"
        state: absent
