---
# Configuring pacman to update mirror list every week using reflector.
- name: Configure pacman and set anacron job for reflector
  hosts: all
  become: yes
  tasks:

    - name: Ensure reflector is installed
      pacman:
        name: reflector
        state: present

    - name: Ensure cronie (providing anacron) is installed
      pacman:
        name: cronie
        state: present

    - name: Ensure anacron service is enabled and running
      systemd:
        name: anacron
        enabled: yes
        state: started

    - name: Set anacron job for reflector
      copy:
        dest: "/etc/anacron.d/pacman_mirrorupdate"
        content: |
          7 5 pacman.mirrorupdate /usr/bin/reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist && /usr/bin/pacman -Sy
        owner: root
        group: root
        mode: '0644'
      notify: Restart anacron

  handlers:
    - name: Restart anacron
      systemd:
        name: anacron
        state: restarted
