---
- name: Ensure reflector is installed
  pacman:
    name: reflector
    state: present

- name: Ensure cronie (providing anacron) is installed
  pacman:
    name: cronie
    state: present

- name: Ensure anacron service is enabled and running
  systemd:
    name: anacron
    enabled: yes
    state: started

- name: Set anacron job for reflector
  copy:
    dest: "/etc/anacron.d/pacman_mirrorupdate"
    content: |
      7 5 pacman.mirrorupdate /usr/bin/reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist && /usr/bin/pacman -Sy
    owner: root
    group: root
    mode: '0644'

- name: Restart anacron
  systemd:
    name: anacron
    state: restarted

- name: Configure paccache hook to clean package cache
  copy:
    dest: "/etc/pacman.d/hooks/clean_package_cache.hook"
    content: |
      [Trigger]
      Operation = Upgrade
      Type = Package
      Target = *

      [Action]
      Description = Cleaning pacman cache...
      When = PostTransaction
      Exec = /usr/bin/paccache -r
    owner: root
    group: root
    mode: '0644'
